// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttbcziwdfkorkopgouar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0YmN6aXdkZmtvcmtvcGdvdWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTcyMDAsImV4cCI6MjA2ODQ3MzIwMH0.YXh5oftmlBmjW3Ql774QpR5cWHWWHuI-qL6pzoHuUik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});